
---
- name: Install packages for base OS setup
  yum:
    name: "{{  item  }}"
    state: present
  loop: "{{  list_of_packages  }}"

- name: Ensure firewalld started
  service:
    name: "{{ list_firewalld_service }}"
    state: restarted
    enabled: yes

- name: SELinux disabled
  selinux:
    state: disabled

- name: Ensure sysstat started
  service:
    name: "{{ list_sysstat_service }}"
    state: restarted
    enabled: yes
