---
# tasks file for ansible-role-grafana
#Package Installation:
- include_tasks: install_packages.yml
#Install NTP
- include_tasks: install_ntp.yml
#Install Docker
- include_tasks: install_docker.yml
#Pip necessary packages
- include_tasks: pip_install_req.yml
#Initialize influxdb
- include_tasks: initialize_influxdb.yml
#Docker Compose
- include_tasks: docker_compose.yml
#Adding grafana dataresource
#- include_tasks: grafana_datasource_influxdb.yml
#Adding grafana  dashboard
#- include_tasks: grafana_dashboard.yml
#Installing telegraf
- include_tasks: telegraf_install.yml
