$ANSIBLE_VAULT;1.1;AES256
65316431663336316430653437393762306565646263343162663233376335636631653637323037
3936663563666635333432616666393330626164323334310a353331653161653630343463323061
35373231306133383464373637653862626266363235356661356164613331663135336664373962
3231633034373330640a373731326264396436306531613866643962313765333438363861666261
33653763373538303865303133356531616365383339343332333761303539346466653436653431
6531663863633232336163613062393666383062336530663865
