---
# handlers file for ansible-role-grafana
- name: restart docker
  service: "name=docker state={{ docker_restart_handler_state }}"

- name: restart telegraf
  service: "name=telegraf state={{ docker_restart_handler_state }}"
